### ISSUE TITLE
cd fails because curdir is undefined in eshell-autojump-record

### ISSUE THREAD

**Issue by brabalan** [coldnew/eshell-autojump#1]
I'm trying to use autojump and I have installed it as suggested, but it does not work with the current version of emacs (24.5.1). The problem seems to be that eshell uses lexical binding, so the variable curdir is not available when running the hook `eshell-autojump-record`.

**Comment by coldnew** [comment]
I think this problem should fixed in commit 4972950, I'll bump a new version.
thanks :)

**Comment by brabalan** [comment]
It works great, thanks a lot.
